server:
  port: 8080

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ds4eRXQlMQq3ONupRsyvb7LCeApLLXmB
            client-secret: EE8lU21zLH-pJgVLwinrp8rjlSGWEJqJ_jA-45QlMLusRqn8g5yPLcL9vZ_Plu7E
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-wksvul8eaqh3wabu.us.auth0.com/
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: Clp12345
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_nationalized_character_data: true
    defer-datasource-initialization: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds
